"""migration waste table

Revision ID: 0415c5fcdc63
Revises: 2c341a3ec190
Create Date: 2025-02-12 19:18:07.860731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0415c5fcdc63"
down_revision: Union[str, None] = "2c341a3ec190"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "Accrual_History", ["id"])
    op.create_unique_constraint(None, "Reception_Point", ["id"])
    op.create_unique_constraint(None, "Waste", ["id"])
    op.drop_constraint("Waste_reception_point_id_fkey", "Waste", type_="foreignkey")
    op.drop_column("Waste", "reception_point_id")
    op.create_unique_constraint(None, "Work_Schedule", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Work_Schedule", type_="unique")
    op.add_column(
        "Waste",
        sa.Column("reception_point_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "Waste_reception_point_id_fkey",
        "Waste",
        "Reception_Point",
        ["reception_point_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "Waste", type_="unique")
    op.drop_constraint(None, "Reception_Point", type_="unique")
    op.drop_constraint(None, "Accrual_History", type_="unique")
    # ### end Alembic commands ###
