"""migration user table

Revision ID: 04eb86a566dd
Revises: d13bfc41e782
Create Date: 2025-02-01 19:21:43.023065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04eb86a566dd"
down_revision: Union[str, None] = "d13bfc41e782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("verification_code", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "User",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_unique_constraint(None, "User", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="unique")
    op.drop_column("User", "updated_at")
    op.drop_column("User", "created_at")
    op.drop_column("User", "verification_code")
    # ### end Alembic commands ###
