"""translation migration

Revision ID: c1b2d7901cbc
Revises: 5a09fb2c83e2
Create Date: 2025-04-26 17:50:22.581866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1b2d7901cbc"
down_revision: Union[str, None] = "5a09fb2c83e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Waste_Translation",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("waste_id", sa.Uuid(), nullable=False),
        sa.Column(
            "languagecode", sa.Enum("RU", "EN", name="languagecode"), nullable=False
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["waste_id"], ["Waste.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("waste_id", "languagecode", name="uq_waste_lang"),
    )
    op.add_column(
        "Reception_Point",
        sa.Column("latitude", sa.Float(), server_default="0.0", nullable=False),
    )
    op.add_column(
        "Reception_Point",
        sa.Column("longitude", sa.Float(), server_default="0.0", nullable=False),
    )
    op.drop_column("Waste", "description")
    op.drop_column("Waste", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Waste",
        sa.Column("name", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    )
    op.add_column(
        "Waste",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("Reception_Point", "longitude")
    op.drop_column("Reception_Point", "latitude")
    op.drop_table("Waste_Translation")
    # ### end Alembic commands ###
