"""migration user and point

Revision ID: 8e5b511824af
Revises: 381ba767cd63
Create Date: 2025-05-11 13:24:51.027354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e5b511824af"
down_revision: Union[str, None] = "381ba767cd63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Reception_Point_Submission",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reception_point_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reception_point_id"], ["Reception_Point.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "reception_point_id"),
    )
    op.drop_table("Moderation")
    op.drop_constraint(
        "Reception_Point_user_id_fkey", "Reception_Point", type_="foreignkey"
    )
    op.drop_column("Reception_Point", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Reception_Point",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "Reception_Point_user_id_fkey",
        "Reception_Point",
        "User",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "Moderation",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "verification_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("reception_point_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["reception_point_id"],
            ["Reception_Point.id"],
            name="Moderation_reception_point_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name="Moderation_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="Moderation_pkey"),
    )
    op.drop_table("Reception_Point_Submission")
    # ### end Alembic commands ###
