"""migration user

Revision ID: 381ba767cd63
Revises: ca077c438eb0
Create Date: 2025-05-09 17:12:01.749068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "381ba767cd63"
down_revision: Union[str, None] = "ca077c438eb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "birth_date")
    op.drop_column("User", "first_name")
    op.drop_column("User", "middle_name")
    op.drop_column("User", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "last_name", sa.VARCHAR(length=32), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "middle_name", sa.VARCHAR(length=32), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "first_name", sa.VARCHAR(length=32), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "User", sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
