"""create waste_table

Revision ID: 6cf1a364f17a
Revises: 80ce9d83baa4
Create Date: 2025-02-11 17:21:58.198127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6cf1a364f17a"
down_revision: Union[str, None] = "80ce9d83baa4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Waste",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("reception_point_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reception_point_id"],
            ["Reception_Point.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("image_url"),
    )
    op.create_unique_constraint(None, "Work_Schedule", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Work_Schedule", type_="unique")
    op.drop_table("Waste")
    # ### end Alembic commands ###
