"""create drop_off_point_waste_table

Revision ID: 407f2b04c249
Revises: 6cf1a364f17a
Create Date: 2025-02-11 17:22:24.728188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "407f2b04c249"
down_revision: Union[str, None] = "6cf1a364f17a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Drop_Off_Point_Waste",
        sa.Column("waste_id", sa.Integer(), nullable=False),
        sa.Column("reception_point_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reception_point_id"], ["Reception_Point.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["waste_id"], ["Waste.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("waste_id", "reception_point_id"),
    )
    op.create_unique_constraint(None, "Waste", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Waste", type_="unique")
    op.drop_table("Drop_Off_Point_Waste")
    # ### end Alembic commands ###
