"""migration user table

Revision ID: 1242e60b6528
Revises: 04eb86a566dd
Create Date: 2025-02-07 01:03:39.129624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1242e60b6528"
down_revision: Union[str, None] = "04eb86a566dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "verification_code_created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.alter_column(
        "User", "verification_code", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "verification_code",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("User", "verification_code_created_at")
    # ### end Alembic commands ###
