"""migration user table

Revision ID: 8d08e3d144ec
Revises: 293a860cd29d
Create Date: 2025-02-11 14:28:04.324746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d08e3d144ec"
down_revision: Union[str, None] = "293a860cd29d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("points", sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "points")
    # ### end Alembic commands ###
