"""migration achievement

Revision ID: 252f4a4c8a3c
Revises: 8e5b511824af
Create Date: 2025-05-11 14:47:35.508844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "252f4a4c8a3c"
down_revision: Union[str, None] = "8e5b511824af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User_Achievement",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("awarded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "achievement_type",
            sa.Enum(
                "FIRST_CONTRIBUTION",
                "FIVE_CONTRIBUTIONS",
                "TEN_CONTRIBUTIONS",
                "ECO_CHAMPION",
                "MAP_MAKER",
                name="achievementtype",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("User_Achievement")
    # ### end Alembic commands ###
