"""migration work schedule table

Revision ID: 611d34aa9db2
Revises: 0415c5fcdc63
Create Date: 2025-02-13 23:36:46.410132

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "611d34aa9db2"
down_revision: Union[str, None] = "0415c5fcdc63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Work_Schedule", "open_time", existing_type=postgresql.TIME(), nullable=True
    )
    op.alter_column(
        "Work_Schedule", "close_time", existing_type=postgresql.TIME(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Work_Schedule", "close_time", existing_type=postgresql.TIME(), nullable=False
    )
    op.alter_column(
        "Work_Schedule", "open_time", existing_type=postgresql.TIME(), nullable=False
    )
    # ### end Alembic commands ###
