"""migration waste and reception poin

Revision ID: 9b36da47b7cc
Revises: 611d34aa9db2
Create Date: 2025-02-20 18:07:57.935744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b36da47b7cc"
down_revision: Union[str, None] = "611d34aa9db2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Reception_Point", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "Waste", sa.Column("abbreviated_name", sa.String(length=32), nullable=False)
    )
    op.create_unique_constraint(None, "Waste", ["abbreviated_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Waste", type_="unique")
    op.drop_column("Waste", "abbreviated_name")
    op.drop_column("Reception_Point", "description")
    # ### end Alembic commands ###
