"""create work_schedule_table

Revision ID: 80ce9d83baa4
Revises: 47d79bda023b
Create Date: 2025-02-11 17:21:24.641839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80ce9d83baa4"
down_revision: Union[str, None] = "47d79bda023b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Work_Schedule",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("open_time", sa.Time(), nullable=False),
        sa.Column("close_time", sa.Time(), nullable=False),
        sa.Column("reception_point_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reception_point_id"],
            ["Reception_Point.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "Reception_Point", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Reception_Point", type_="unique")
    op.drop_table("Work_Schedule")
    # ### end Alembic commands ###
