volumes:
  postgresql-data: {}
  minio-data: {}

networks:
  backend-ecos:
    name: backend-ecos
    driver: bridge

services:
  postgresql-ecos:
    container_name: postgresql-ecos
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    networks:
      - backend-ecos
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
   